### ISSUE TITLE
[Bug] "Comment count" filter broken in steam search page

### ISSUE THREAD

**Issue by WilliamStone** [tfedor/AugmentedSteam#1159] opened 2021-05-28 16:17 UTC
Hi, 
  In steam search page, Augmented Steam adds a few filters to help we users to hide unwanted games, among which is this "Comment count"(评测数) filter, which is broken.
  I use Chinese version, and I'm not sure whether English name of the filter is correct, so I marked the filter out using red box in the snapshot.
  The problem is: If input any number in left box, ALL GAMES are filtered out. And if input any number in right box, it seems do nothing.
  The filter is very useful, because without it the "score range" filter cannot work perfectly, i.e. it cannot filter out those games having less than 10 comments and doesn't have a score. As regarding this, I also suggest change behavior of "score range" and filter out those games without a score.
  Please check the bug, thanks!

![image](https://user-images.githubusercontent.com/3304300/120012147-b777f080-c011-11eb-94db-73947bc7e590.png)

**Comment by candela97** [comment] 2021-05-28 18:43
Duplicate of #1036

**Comment by MxtOUT** [comment] 2021-10-18 09:16
Hey, the gif you sent is using the review count filter (which I assume is meant here by "comment count"), which is fixed by the commit closing #1036

**Closed by MxtOUT** 2021-10-18 09:16 UTC
