### ISSUE TITLE
Uncaught (in promise) errors

### ISSUE THREAD

**Issue by C-O-S** [tfedor/AugmentedSteam#260] opened 2019-05-02 11:23 UTC
Using Chrome Version 74.0.3729.131 (Official Build) (64-bit) and Augmented Steam 0.9.6:

After uninstalling and reinstalling the extension it seems to work for awhile.  Later the highlighting stops working and the Augmented Steam logo at the top of the screen stops displaying.  

When checking the console I see the following errors displayed:

![Annotation 2019-05-02 072202](https://user-images.githubusercontent.com/33273295/57072231-ff997d00-6caa-11e9-8e89-9c6363b5890f.png)

**Comment by MxtOUT** [comment] 2019-05-02 11:25
Yes, we are aware of this error and the cause seems to be server sided

**Comment by C-O-S** [comment] 2019-05-02 11:28
OK - thanks for letting me know.  😃

**Comment by C-O-S** [comment] 2019-05-03 00:40
Just FYI - also catching them here:

![Annotation 2019-05-02 203906](https://user-images.githubusercontent.com/33273295/57115030-62762d00-6d1a-11e9-8f0e-fe82659d8e39.png)

**Comment by xPixv** [comment] 2019-05-03 13:43
Same error in https://steamcommunity.com/my/home/

![image](https://user-images.githubusercontent.com/9652227/57141227-578bcd00-6dec-11e9-836f-279606a4f848.png)

**Comment by MxtOUT** [comment] 2019-05-22 16:35
@C-O-S @xPixv Sadly I cannot debug these errors personally because I don't have any coupons in my inventory.
But if you'd take your time and report some values to me, that would be useful :)

To do that, press F12, go on the sources tab and look for the file common.js from Augmented Steam.
Open it and set a breakpoint on line number 1261. Reload the page, the breakpoint should get triggered.
Switch to the Console tab, type in `coupons`, confirm and report the value that has been printed to the console.

**Comment by xPixv** [comment] 2019-05-22 17:39
> @C-O-S @xPixv Sadly I cannot debug these errors personally because I don't have any coupons in my inventory.
> But if you'd take your time and report some values to me, that would be useful :)
> 
> To do that, press F12, go on the sources tab and look for the file common.js from Augmented Steam.
> Open it and set a breakpoint on line number 1261. Reload the page, the breakpoint should get triggered.
> Switch to the Console tab, type in `coupons`, confirm and report the value that has been printed to the console.

Hi MxtOUT,
Thank you for your reply. This problem seems no longer shown. (about days after I report it)
If it shows one day, I'll follow your step and provide more details. :)

Thank you for your work.

**Comment by C-O-S** [comment] 2019-05-22 23:38
> common.js:1993  Augmented Steam v0.9.6  https://es.isthereanydeal.com/
coupons
{210148: {…}}210148: appids: [{…}]discount: "33"discount_doesnt_stack: truediscount_note: "Can't be applied with other discounts."discount_note_id: 1id: "2710571255_3287263110"image_url: "IzMF03bk9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdB3Yhlc0A8FYDBb3UGq5BUckz8k2QU5PUl8J-kDVZxnpDOCezjlArYex_O8TTzhGm8rHLCG3nbWqUaTLQBls1TKUCOD2HqW_8prWCBDXIdz_PKbQ"title: "33% OFF Sniper Hunter Adventure 3D"valid: "(Valid until [date]1559170800[/date])"valid_id: 3__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()

**Comment by MxtOUT** [comment] 2019-05-23 07:30
Could you expand the `appids` property as far as you can?

**Comment by C-O-S** [comment] 2019-05-23 10:50
![Annotation 2019-05-23 064845](https://user-images.githubusercontent.com/33273295/58247209-0e61d580-7d27-11e9-9ac2-897c2ba84709.png)

> common.js:1993  Augmented Steam v0.9.6  https://es.isthereanydeal.com/
coupons
{210148: {…}}210148: appids: Array(1)0: id: 723190name: "Sniper Hunter Adventure 3D"__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()length: 1__proto__: Array(0)concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()discount: "33"discount_doesnt_stack: truediscount_note: "Can't be applied with other discounts."discount_note_id: 1id: "2710571255_3287263110"image_url: "IzMF03bk9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdB3Yhlc0A8FYDBb3UGq5BUckz8k2QU5PUl8J-kDVZxnpDOCezjlArYex_O8TTzhGm8rHLCG3nbWqUaTLQBls1TKUCOD2HqW_8prWCBDXIdz_PKbQ"title: "33% OFF Sniper Hunter Adventure 3D"valid: "(Valid until [date]1559170800[/date])"valid_id: 3__proto__: Object__proto__: Object

**Comment by MxtOUT** [comment] 2019-08-07 10:34
I will close this for now, because the problem initially described here is basically #271.
The second error (`details.appids is not iterable`) should be fixed by now, but feel free to reopen (or probably better, to create a new issue) if it isn't

**Closed by MxtOUT** 2019-08-07 10:34 UTC
