### ISSUE TITLE
[BUG] extension breaks SteamDB's app pages' buttons on Firefox

### ISSUE THREAD

**Issue by fmbarina** [tfedor/AugmentedSteam#1768] opened 2023-09-14 14:19 UTC
I wasn't sure where to report this, so if you think this would be better shared in SteamDB's extension [issue tracker](https://github.com/SteamDatabase/BrowserExtension/issues), I can do that and perhaps even close this issue too. There seems to be [interest](https://github.com/IsThereAnyDeal/AugmentedSteam/issues/47#issuecomment-520780549) in letting these extensions coexist, so hopefully this counts as a bug.

### Expected Behavior

With the SteamDB extension installed, you may optionally add these two links to the left of the community hub button:

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/70731450/b86d3dba-e0fc-4ba1-99a5-52d1899123bb)

### Actual Behavior

With Augmented Steam enabled alongside SteamDB on Firefox, this happens:

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/70731450/160cac0a-6f4e-4985-8d2b-b669e91d1a09)
(sometimes they "shrink" after a short pause, which I guess is Augmented Steam loading)

### Steps to Reproduce the Problem

  1. Install both Augmented Steam and SteamDB extensions on Firefox
  2. Open any app page

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Firefox: 117.0

### Notes

- I say "on Firefox" because a quick test on chromium (via Vivaldi) didn't show the same issue. 
- It made no difference when I...
  - reset the Augment Steam extension settings
  - disabled all extensions besides these two
- There's a workaround, sort of...? SteamDB lets you disable both links and Augmented Steam provides alternatives. 

Checking the console on Firefox showed me an error, but I don't know if it's related to the issue. 
`TypeError: e is null[AugmentedSteam.js:200:28](webpack://augmented-steam/src/js/Content/Modules/AugmentedSteam.js)`

I'll try to investigate more later and post here if I find anything interesting.

**Comment by candela97** [comment] 2023-09-14 15:41
Duplicate of #1692

**Closed as not planned by candela97** 2023-09-14 15:41 UTC
Labels: bug, duplicate
