### ISSUE TITLE
[BUG] additional links doesn't get added

### ISSUE THREAD

**Issue by SonOfDiablo** [tfedor/AugmentedSteam#1196] opened 2021-06-17 16:03 UTC
### Expected Behavior
Links such as SteamDB, IsThereAnyDeal, AStats, etc. would be added to the store page

### Actual Behavior
None of the links is added to the store page

### Steps to Reproduce the Problem

  1. Go to a steam store page (example https://store.steampowered.com/app/512900/Streets_of_Rogue/)

### Specifications

  - Augmented Steam Version: 2.0.1
  - Browser Version : Vivaldi 4.0.2312.27

Messages from the console:
```
app.js:1  Augmented Steam v2.0.1  https://augmentedsteam.com
app.js:1 V
app.js:1 Error while applying feature V
(anonymous) @ app.js:1
app.js:1 DOMException: Failed to execute 'insertAdjacentElement' on 'Element': The new child element contains the parent.
    at V._moveExtraLinks (chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/js/store/app.js:1:67738)
    at V.apply (chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/js/store/app.js:1:65229)
    at chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/js/store/app.js:1:136695
(anonymous) @ app.js:1
app.js:1 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request. https://goo.gl/LdLk22
app.js:1 Feature loading complete, 28 successfully loaded, 1 failed to load, 0 didn't load due to dependency errors
DevTools failed to load source map: Could not load content for chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/js/store/app.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

![image](https://user-images.githubusercontent.com/9123250/122433204-4be0cd80-cf96-11eb-8eca-07e9dc149ce1.png)

**Comment by Revadike** [comment] 2021-06-17 17:16
Another hour, another dupe of #1175

**Closed** 2021-06-17 17:56 UTC
Labels: bug
