### ISSUE TITLE
Stuck at winter profile theme

### ISSUE THREAD

**Issue by Shinkei6290** [tfedor/AugmentedSteam#915] opened 2020-06-26 22:01 UTC
I cant disable winter profile theme.
When i uninstall extension it disappear, and when I install the extension again, it reappears.
I think that earlier there was an option to change the theme, but now I cant find it.

**Comment by Revadike** [comment] 2020-06-26 22:38
dupe of https://github.com/tfedor/AugmentedSteam/issues/913

**Comment by Shinkei6290** [comment] 2020-06-27 06:03
Thanks

**Closed** 2020-06-27 06:03 UTC
