### ISSUE TITLE
Sort options on groups page and friends page disappear after switching tabs

### ISSUE THREAD

**Issue by candela97** [tfedor/AugmentedSteam#768] opened 2020-02-08 09:21 UTC
https://steamcommunity.com/my/groups/
Have to reload the page to get them to show again. Is it because only the nodes on the page are updated?

**Comment by Revadike** [comment] 2020-02-08 13:55
Dupe of https://github.com/tfedor/AugmentedSteam/issues/375

**Closed** 2020-02-08 15:13 UTC
