### ISSUE TITLE
[BUG] "Suggest a new category" is not worked

### ISSUE THREAD

**Issue by Korb** [tfedor/AugmentedSteam#1123] opened 2021-03-21 06:23 UTC
### Expected Behavior
Clicking on the "Suggest a new category" link opens a new window in which you can select a new category.

### Actual Behavior
On the page of the game "Age of Empires II: Definitive Edition - Lords of the West", clicking on the link opens a new tab with the text "404 Not Found. Nginx".

### Steps to Reproduce the Problem

1. Open in the browser Mozilla Firefox with the Augmented Steam add-on https://store.steampowered.com/app/1389240
2. Click on the link "[Suggest a new category](https://augmentedsteam.com/gamedata/dlc_category_suggest.php?appid=1389240&appname=Age of Empires II: Definitive Edition - Lords of the West)"

### Specifications

  - Augmented Steam Version: 2.0.1 (March 9, 2021) 
  - Browser Version : 87.0 (64-bit)

**Comment by Revadike** [comment] 2021-03-21 14:22
@tfedor should be assigned for this

**Comment by candela97** [comment] 2021-03-25 13:36
Duplicate of #1081.

**Closed** 2021-04-01 10:43 UTC
Labels: bug
