### ISSUE TITLE
QUOTA_BYTES_PER_ITEM quota exceeded

### ISSUE THREAD

**Issue by bluedasher13** [tfedor/AugmentedSteam#943] opened 2020-09-04 12:38 UTC
While I edit the notes of apps, I got an error message  "QUOTA_BYTES_PER_ITEM quota exceeded" in the console.

It seems that [the quota of the extension is 5242880 bytes](https://stackoverflow.com/questions/33015723/unchecked-runtime-lasterror-while-running-storage-set-quota-bytes-per-item-quot):
[https://stackoverflow.com/questions/33015723/unchecked-runtime-lasterror-while-running-storage-set-quota-bytes-per-item-quot](https://stackoverflow.com/questions/33015723/unchecked-runtime-lasterror-while-running-storage-set-quota-bytes-per-item-quot)

But I want to save more notes.

**Comment by MxtOUT** [comment] 2020-09-24 13:27
Duplicate of #848

**Closed by MxtOUT** 2020-09-24 13:27 UTC
