### ISSUE TITLE
Steam DB extension integration

### ISSUE THREAD

**Issue by azumukupoe** [tfedor/AugmentedSteam#47] opened 2019-02-13 20:42 UTC

**Comment by tfedor** [comment] 2019-02-14 21:40
What do you mean by this?

**Comment by Tmp341** [comment] 2019-03-07 06:23
I guess, he means "merging 2 extensions into this one".

**Comment by tfedor** [comment] 2019-03-07 22:01
Closing for lack of info.

**Comment by Revadike** [comment] 2019-08-11 20:31
No need to close this. I actually agree. It would be nice to have all the non-steamdb specific features of the [steamdb extension](https://github.com/SteamDatabase/BrowserExtension) by @SteamDatabase integrated.
Here is a list I compiled:
 * Display SubID under each purchase option
 * Display SubID in app widgets
 * Link each package on your accounts page
 * Move game selection on inventory page to the side
 * Link each gift and coupon (from: View applicable games) in your inventory to SteamDB
 * Correctly figure out gift SubID in your inventory
 * Display item market price in other users' inventories
 * Support for_item in tradeoffer urls
 * Offer better error messages in trade offers, instead of Valve's cryptic error numbers
 * Display hidden achievements (and their descriptions) on your achievements page
 * Improve global achievements page: locked achievements are more visible, hidden achievement descriptions, link to your own achievements page
 * Adds a button to cheat the discovery queue during sales
 * Center store homepage properly on big screens
 * Add a block on Steam Store app pages displaying lowest recorded price (for Steam store only!)
 * Add a block on Steam Store displaying online stats
 * Remove all linkfilter links (visiting linkfilter still works)
 * Stop images from loading on app store pages. Many developers put multiple megabytes of images in game descriptions which usually takes a while to load. Click on an image to load.

I think that makes it worth reopening @tfedor .

**Comment by Revadike** [comment] 2019-08-13 02:19
Also, DEPOTS UPDATE feature in app store pages.

**Comment by Revadike** [comment] 2019-08-13 02:28
Also, SteamDB rating.

**Comment by Revadike** [comment] 2019-08-13 02:33
https://github.com/tfedor/AugmentedSteam/issues/215

**Comment by xPaw** [comment] 2019-08-13 07:23
SteamDB ext is my testbed essentially, and I wouldn't really want you carbon-copy entirety of it into this extension.

> Seems to be retrieved from this API: https://steamdb.info/api/GetCurrentPlayers/?appid=440&source=extension_steam_store

Yes our extension uses it, but that doesn't really mean other extensions should start relying on it too.

**Comment by tfedor** [comment] 2019-08-13 10:29
@xPaw I don't want to carbon copy your extension and I certainly wouldn't allow using your API. I don't want any bad blood between us (quite the opposite).

I don't have any aspiration to start tracking depot updates and other under the hood Steam stuff, that's not what Augmented Steam is for. Augmented Steam and SteamDb extension should be able to coexist, but there is and will be overlap unfortunately. 

I don't know whether there is something we should add yet, I reopened it because there were new updates. But the fact that the issue is reopened does not mean features from SteamDb extension will be implemented.

**Comment by xPaw** [comment] 2019-08-13 10:31
Feature overlap is fine, I have options to turn most of the features, so it can be avoided if they conflict. On my side of things, I usually ignore feature requests that asked "add X from enhanced steam" as it's rather useless to copy the feature over.

**Comment by tfedor** [comment] 2019-08-13 10:56
Yup, I completely agree, we have options to turn almost everything off as well.

I think I can close this again. I'd like to reiterate one last time that it's by no means our intention to just copy your (or any other) extension to AS. As you said, there's no reason for that.

**Closed by tfedor** 2019-08-13 10:56 UTC

**Comment by Revadike** [comment] 2019-08-13 13:09
Yeah, I'm fine with keeping them separate. I think actually, it is better to keep the steamdb stuff in its own extension.
As for the overlap, I may have a solution. AG could detect if SteamDB extension is present and modify its options accordingly, or present a SteamDB extension compatibiliy mode.
@xPaw what would help for this, is if you could somehow pass your extension options object onto us, e.g. via a global variable.

**Comment by Revadike** [comment] 2021-05-12 23:54
Why is this marked as closed & done? There are some excellent suggestions in this, imo. I especially like the compatibility mode feature I suggested above.

**Comment by Exazinho** [comment] 2024-07-06 18:08
it could be really cool to have an option to either disable duplicate functions on either the steamdb or augmented steam side.

**Comment by candela97** [comment] 2024-07-12 16:11
@Exazinho Please log a new issue if you have any specific features/settings in mind. We try to be compatible with SteamDB and not create duplicate/conflicting features.
