### ISSUE TITLE
[Feature Request] Wishlist: show Rank Edit box even when filter is applied

### ISSUE THREAD

**Issue by gab** [tfedor/AugmentedSteam#650] opened 2019-11-17 18:32 UTC
Currently it's pretty much impossible to sort games in your wishlist if you have a lot (like 600) in there. Ctrl-f doesn't find the game because the whole thing isn't loaded all at once, and if you filter to find the game, you suddenly don't have the box where you can type to change the rank.

Please step in once more to fix Steam's oversights.

**Comment by Revadike** [comment] 2019-11-18 00:01
Dupe of https://github.com/tfedor/AugmentedSteam/issues/337

**Closed** 2019-11-20 11:26 UTC
Labels: augmentation, duplicate
