### ISSUE TITLE
[BUG] None of the Sidebar Link Additions on Augmented are working.

### ISSUE THREAD

**Issue by Black3ird** [tfedor/AugmentedSteam#1211] opened 2021-06-30 14:01 UTC
### Expected Behavior
Until past month, the Options on Augmented Steam's `Options for information from 3rd-party sites` linking for Metacritic, Opencritic, HowLongToBeat, IsThereAnyDeal, SteamDB, Barter, AStats, YouTube, Twitch, PCGamingWiki, Completionist.me , ProtonDB, WSGF, SteamCardExchange, SteamCharts were showing at the right sidebar of every Steam game page since their checkboxes were checked.

And result was like (Google search, right side of image)
![Right Side of Image](https://lh3.googleusercontent.com/0JZy2GIKBHhdIa65vB8BVKh_dus_GhMMOzvV5bze0yB_TfcdmR-Yy1MF2n0cQm6vChzfBa1FguolFDb8KAM48k7N9g=w640-h400-e365-rj-sc0x00ffffff)
that shows only the 5 options out of available 18 linkings.

### Actual Behavior
Now it shows nothing in the same area even if tried it on latest Chrome and latest Firefox on empty Profiles so to eliminate all interference from settings and extensions but only Augmented Steam installed. Rest of all the functions from Augmented Steam works, but the sidebar linkings had disappeared. I even tried to change DNS or Network or even VPN to eliminate further suspicion.

### Plausible Theory
Valve "changed" something in their Steam Store pages like an anchor that Augmented Steam was using to "inject" their code into Steam Page but now that anchor being changed to something else, this function becomes defunct as there's nothing to anchor to so there's nothing shown. I can't be sure of this but I've been an advanced uBlock user and knowing intermediate CSS to "inject" or find my anchors (selector or whatever they're called) in HTML pages so that making an educated guess here.

### Steps to Reproduce
  1. Install latest Chrome or Firefox  
  2. Install latest Augmented Steam from its extension page  
  3. Don't change any setting on it (because default settings has some linkings auto enabled)  
  4. Visit "any" Steam store Game page like https://store.steampowered.com/app/570/Dota_2/  
  5. Observe the right sidebar that were supposed to be added new links because of Augmented
  6. Notice that nothing is there like it was before

### Temporary Solution
Thanks to many Userscripts like on https://greasyfork.org/en/scripts/26273-steam-web-integration and via Chrome `Context Menu Search` extension I was able to somewhat restore of broken Augmented Steam functionality to some degree for those missing 18 linkings to 3rd party sites but this isn't a robust solution like Augmented was in few weeks prior to this "Bug".

### Specifications

  - Augmented Steam Version: 2.0.1 (funny that Augmented's own about on chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/html/options.html doesn't have version info)  
  - Browser Version : 91.0.4472.124 (Official Build) (64-bit) for Chrome

If anyone else not seeing those, please post back so that I may try different routes in deduction process to find the cause of the bug I'm seeing. Thanks for your time for reading and this great extension.

**Comment by MxtOUT** [comment] 2021-06-30 16:20
Duplicate of #1175

**Closed by MxtOUT** 2021-06-30 16:20 UTC
Labels: bug
