### ISSUE TITLE
YouTube Reviews video has an invalid ID

### ISSUE THREAD

**Issue by avi12** [tfedor/AugmentedSteam#936] opened 2020-08-06 21:23 UTC
This typically happens when a game has yet to be released or has just been released.
In such a case, the `YouTube Reviews` tab should simply be disabled & grayed out, to indicate that no video is available.

**Comment by MxtOUT** [comment] 2020-08-15 15:24
I spent quite some time on trying to find a solution to this problem.
You're not able to detect the length of the search results reliably with the functions that the YT Player API provides.

**Comment by alphatonic** [comment] 2020-09-08 11:43
I have it with every single game page.

**Comment by scharmach** [comment] 2020-09-09 15:11
> 
> 
> I have it with every single game page.

Same here and not only for `YouTube Reviews`, but for `YouTube Gameplay` too.

When clicking on the tabs the YouTube-player loads like this, with no videos queued and only a black background:

![grafik](https://user-images.githubusercontent.com/9080980/92617214-565f8f80-f2bf-11ea-98cf-ab7da47e2e43.png)

And when I click on the play-button I then get to see this:

![grafik](https://user-images.githubusercontent.com/9080980/92617072-39c35780-f2bf-11ea-8526-c2998d385dc0.png)

**Comment by rohithpalagiri** [comment] 2020-09-11 00:07
Also receiving this issue. Disabled all my ad blockers and pihole to see if it had something to do with queries being blocked. No luck though, this is affecting Youtube Gameplay and Youtube Review tabs.

**Comment by scharmach** [comment] 2020-09-11 15:26
Don't know what has changed, but it is working again, at least for me.

**Comment by MxtOUT** [comment] 2020-09-12 12:29
It looks like the error is on YT's side, so your best bet is to just wait and hope that it recovers

**Comment by 1roha** [comment] 2020-10-15 23:42
same issue, I just found out it was caused by another exstension (Good Old Youtube) 
solved by removing it

**Comment by 1roha** [comment] 2020-12-06 15:29
the feature seems broken now

**Comment by candela97** [comment] 2020-12-06 16:37
> the feature seems broken now

looks like [`listType=search` has been deprecated since 15 November](https://developers.google.com/youtube/player_parameters#listType)

**Comment by candela97** [comment] 2020-12-06 21:26
> the feature seems broken now

@MxtOUT looks like [`listType=search` has been deprecated since 15 November](https://developers.google.com/youtube/player_parameters#release_notes_10_13_2020)

**Comment by MxtOUT** [comment] 2021-01-12 10:55
Since we will temporarily disable the YouTube video player for the next version and afterwards implement it on the server side, we will be able to detect whether or not there are any videos for a given app.
Therefore I'm closing this issue

**Closed by MxtOUT** 2021-01-12 10:55 UTC
