### ISSUE TITLE
[Suggestion] Re add HD toggle to game store videos

### ISSUE THREAD

**Issue by BarterClub** [tfedor/AugmentedSteam#40] opened 2019-02-13 01:06 UTC
This seems to be removed for some reason and it was a very nice thing to have. I like to see the game im going to get in HD. Not the steam auto resolution that you can't change.

**Comment by KarlCastle** [comment] 2019-02-13 09:29
This is a bug :(

tfedor/Enhanced_Steam#31 was intended to fix it and didn't make it into 0.9.2, so the feature was patched out with tfedor/Enhanced_Steam@42ecaad2b01c084813d8fcaeb7c6f9fe74182cce

Since the patch has been merged, the feature should be back in the next release :)

**Comment by KarlCastle** [comment] 2019-02-22 17:48
The HD button is back for me in 0.9.3, is it still missing for you?

**Comment by tfedor** [comment] 2019-03-07 22:00
Still needs to be added to shared files in Community

**Comment by KarlCastle** [comment] 2019-04-19 03:33
Enhanced Steam had the "theater mode" expander on Community videos, it didn't have the HD button as the videos are all hosted on YouTube with the embedded YouTube player rather than the Steam media player applet.  I think this can be closed.

**Comment by tfedor** [comment] 2019-04-19 12:21
Done

**Closed by tfedor** 2019-04-19 12:21 UTC
Labels: bug
