### ISSUE TITLE
[Feature Request] Export+Import settings

### ISSUE THREAD

**Issue by metapone** [tfedor/AugmentedSteam#591] opened 2019-10-21 15:11 UTC
Syncing through Firefox/Chrome account is also an option, but I think this solution would be more portable.

**Comment by DAOWAce** [comment] 2019-10-23 04:32
I just found out about this addon after looking up issues with the store page caused by ES.

Would really like a config import from the old addon to this one rather than being forced to go through and reconfigure everything..

**Comment by clst** [comment] 2019-10-28 23:07
You can read the settings from the options page in chrome on the Console yourself:

`chrome.storage.sync.get(function(data){console.log(JSON.stringify(data))})`

If you use chrome without account replace `sync` with `local`.

This will dump all settings as JSON. BUT sadly this fork isn't 100% compatible with ES settings anymore and crashes when you just import the whole thing :(
It should work with the same version of Augmented Steam however.

I haven't looked much more into it right now.

**Comment by clst** [comment] 2019-10-28 23:16
Update: But only for people with the knowledge to do so (breaking the settings will break the extension for good including syncing broken settings so a reinstall won't fix it again since the reset settings button is inoperable).

If you leave out the stores hash from your old ES settings you can just dump the whole thing into Augmented Steam's storage and it'll work.

**Comment by Revadike** [comment] 2019-10-28 23:20
Cool, now we just need a good UI. I was thinking just a generic import/export section in the options.

**Comment by clst** [comment] 2019-10-28 23:56
Some things definitely need tweaking. My language imported as empty but there have been no errors.
My advice would be to put a version number on the export (or even a sort of checksum) and verify that. Just so that people don't accidently break their install.

Also some sort of try/catch for the Options function would prevent total breakage in case of an error,

Thanks for maintaining this :+1:  :1st_place_medal:

**Comment by Revadike** [comment] 2019-10-29 00:06
I encourage you to make a pull request!

**Comment by clst** [comment] 2019-10-29 17:57
I'd love to but I am afraid I don't have the time. :(

**Comment by GlassedSilver** [comment] 2020-03-20 08:04
Baffled to see this extension have so many settings to configure and no import/export tool.

**Closed** 2020-04-17 13:46 UTC
Labels: augmentation

**Comment by DAOWAce** [comment] 2020-05-31 15:46
@MxtOUT Belated thank you for the addition.

**Comment by GlassedSilver** [comment] 2020-05-31 21:42
Likewise from me! Super stoked and very glad! Many many thanks!
