### ISSUE TITLE
[BUG] No ITAD Links showing

### ISSUE THREAD

**Issue by Meridiian** [tfedor/AugmentedSteam#1192] opened 2021-06-14 07:19 UTC
I am no longer getting the view on ITAD page links on any of the games or on the context menu. Actually I am not sure any of the Augmented Steam functionality is working. I just tried removing the extension, clearing my cache and cookies and reinstalling but still not working.

Just tried to install the extension in Microsoft Edge just to see if it was a browser issue but not working in Edge either.

  - Augmented Steam Version: 2.0.1
  - Browser Version : Google Chrome 91.0.4472.101 (Official Build) (64-bit)

**Comment by andrewpros** [comment] 2021-06-14 10:45
I can confirm latest firefox the same, its all button links that are on top, not only ITAD, steamDB etc. but if its on bottom like opencritic or howlongtobeat it works.

Something changed, the error shows  only if extension is enabled.

[](https://i.imgur.com/Fj9TG6v.png)

**Comment by Revadike** [comment] 2021-06-14 11:38
> I can confirm latest firefox the same, its probably all links/data that are on top, not only ITAD, steamDB too etc. but if its the bottom data like opencritic or howlongtobeat it works.
> 
> Something changed, the error shows only if extension is enabled.
> 
> ![](https://camo.githubusercontent.com/c92473c1f77c4086370b14d68a1a2937031de185f89f493504f568cf722c907d/68747470733a2f2f692e696d6775722e636f6d2f466a39544736762e706e67)

Already reported (https://github.com/tfedor/AugmentedSteam/issues/1175) and fixed in the dev branch

**Comment by candela97** [comment] 2021-06-14 16:18
Context menu links have to be enabled in options for them to show up. As for 3rd party links on app pages not showing, this is an issue due to recent Steam changes and will be fixed in the next version.

**Comment by Meridiian** [comment] 2021-06-14 22:07
The options are enabled.

**Comment by MxtOUT** [comment] 2021-06-15 11:01
Duplicate

**Closed by MxtOUT** 2021-06-15 11:01 UTC
Labels: bug
