### ISSUE TITLE
[Bug] Transaction Summary value wrong

### ISSUE THREAD

**Issue by GenBill** [tfedor/AugmentedSteam#781] opened 2020-02-16 16:18 UTC
I am using CNY as my steam currency and Simplified Chinese as my main language.
I found my Transaction Summary is wrong. 
For example, I have sold at least 1000 CNY in the market, but the value shown here is much lower than 1000. 
Maybe you confused CNY and JPY units, because they have the same symbol. 
I used EnhancedSteam several months ago, it show me an correct value. And I have recorded these values(A).
Now AugmentedSteam show me an values(B). I found A≈B*15, and 1 CNY≈15 JPY. This may confirm my guess. 
I thought the problem would be discovered and fixed soon, but months passed.
You guys should probably check the code which related to CNY.

**Comment by MxtOUT** [comment] 2020-02-17 16:25
Duplicate of #656

**Closed by MxtOUT** 2020-02-17 16:25 UTC
Labels: duplicate
