### ISSUE TITLE
Extension partially interferes with SteamDB extension (UI glitch)

### ISSUE THREAD

**Issue by gmikhail** [tfedor/AugmentedSteam#573] opened 2019-10-14 08:29 UTC
https://github.com/SteamDatabase/BrowserExtension/issues/45
Chrome 77.0.3865.120

**Comment by MxtOUT** [comment] 2019-10-20 19:49
Hm, this is sometimes reproducible, but AS actually doesn't change anything that affects the design of this box directly.
I would guess that this glitch is caused by a specific timing of certain DOM insertions.
Once you hover over the box, it will recalculate and adjust to its proper position.

If you find another cause of this issue, please report it here, but I'll close this for now.

**Closed by MxtOUT** 2019-10-20 19:49 UTC
