### ISSUE TITLE
Inventory - Quick Sell & Instant Sell buttons not loading (Too Many Requests)

### ISSUE THREAD

**Issue by Optimaximal** [tfedor/AugmentedSteam#251] opened 2019-04-26 10:57 UTC
The Quick Sell and Instant Sell buttons sometimes don't load on Inventory Items. The problem seems to be exacerbated by clicking on the actual buttons on other cards then moving onto sell the next item.

Chrome Console *sometimes* shows errors in VM14:1, common.js and community.js relating to 'Too Many Requests', which is probably rate control by the Steam Marketplace API?

If there's no solution, possibly add a built-in refresh after 10-20 seconds or a manual refresh button?

The problem can only be fixed by reloading the page.

**Comment by MxtOUT** [comment] 2019-04-26 15:34
We currently have a similar approach with the lowest market prices that appear in a column in your listings table.

The problem is that the Steam servers don't return a `Retry-After` header which would simplify the process enormously, so we set a static timeout (I believe 40 seconds) and retry after this time.

But the time after which the servers allow further requests increments over time, so yeah, the current solution isn't optimal too

**Comment by KarlCastle** [comment] 2019-04-27 07:53
There's a bug where clicking on an item then moving to the next item before the buttons fully load means they won't appear for that item until the page is reloaded. This is unrelated to any issues from 429/Too Many Requests.

Testing this now, the Too Many Requests errors seem to be from `community.js:1660, InventoryPageClass.showMarketOverview()` (the `common.js` reference is from `common.js:283, RequestData.getJson()`, so it's the same error being reported twice). `showMarketOverview()` is the text:
> Starting at: A$ 0.12
> Average price of three trading cards: A$ 0.09
And is unrelated to the display of the quick/install-sell buttons.

Clicking around, I haven't seen a 429 on the `/market/itemordershistogram` endpoint used by the sell buttons? Only the overview `/market/priceoverview/`, which will be triggered by Valve's code too.

**Closed** 2019-08-07 14:12 UTC
