### ISSUE TITLE
Filtering issues on Browsing page

### ISSUE THREAD

**Issue by WilliamArmstrong** [tfedor/AugmentedSteam#113] opened 2019-03-03 02:26 UTC
Firefox Developer Edition: 66.0b11

There are several issues with the "Hide" filter:
"Items you own": Working
"Items on your wishlist": Working
"Items in your cart": Working
"Items not discounted": Working on first page but the next result set is unfiltered
"Items marked not interested": If this is supposed to filter out things marked as ignored then it doesn't work
"Mixed rating items": Working on first page but the next result set is unfiltered
"Negative rating items": Working on first page but the next result set is unfiltered
"Items that cost more than": Not working

Also, there are two other behaviours that are interesting.  If you have filters selected, they don't show in the tags at the top.  However, if you press "Enter" inside the "Items that cost more than" text box, all selected filters will present themselves in the tags.

Clicking the top tags will untoggle the filters but will not remove the tags.  To remove the tags, you have to untoggle the filters then press "Enter" inside the "Items that cost mroe than" text box.

**Comment by WilliamArmstrong** [comment] 2019-03-03 02:31
![2019-03-02_20-25-55](https://user-images.githubusercontent.com/20190140/53690125-1878c700-3d2a-11e9-94d4-dedad6b0ce96.gif)

**Comment by MxtOUT** [comment] 2019-03-03 13:29
"Items that cost more than" should be fixed with #90,
"Items marked not interested" with #70.

The behavior you noticed was caused by the `submit` action of the input box and should also be fixed with #90 since that messed up the filtering.
These tags are not meant to show up like regular Steam tags.

**Comment by MxtOUT** [comment] 2019-08-07 14:54
Is it fixed?

**Closed** 2019-09-09 12:28 UTC
Labels: bug, more info needed
