### ISSUE TITLE
[BUG] The coloring does not work after changing the sorting conditions during the search

### ISSUE THREAD

**Issue by bestpika** [tfedor/AugmentedSteam#1064] opened 2021-02-15 03:27 UTC
### Expected Behavior

![image](https://user-images.githubusercontent.com/5698157/107902075-59eaf700-6f80-11eb-8721-76c59b035e3b.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/5698157/107902124-7ab34c80-6f80-11eb-8dd1-56f3ff1920f8.png)

### Steps to Reproduce the Problem

1. Search anything.
1. Change the sorting conditions.

### Specifications

- Augmented Steam Version: 2.0.0
- Browser Version: Chrome 86.0.4240.198

**Comment by Revadike** [comment] 2021-02-15 03:35
Duplicate of #1039.

**Closed** 2021-02-26 14:41 UTC
Labels: bug
