### ISSUE TITLE
[BUG] SteamDB link gone missing from store pages

### ISSUE THREAD

**Issue by rgralevsky** [tfedor/AugmentedSteam#1195] opened 2021-06-17 01:48 UTC
### Expected Behavior
There is SteamDB link on every game's store page (if it is enabled in AugmentedSteam)

### Actual Behavior
There is no SteamDB link on every game's store page

### Steps to Reproduce the Problem

  1. Go to any store page
  2. Check the place where SteamDB link usually was
  3. No link

### Specifications

  - Augmented Steam Version: 2.0.1
  - Browser Version: Firefox 89.0.1

**Comment by Revadike** [comment] 2021-06-17 02:31
Dupe of https://github.com/tfedor/AugmentedSteam/issues/1175

**Closed** 2021-06-17 12:14 UTC
Labels: bug
